package com.xteam.asc4j.module.entities;

/**
 * PurviewFunNode generated by MyEclipse Persistence Tools
 */

public class PurviewFunNode implements java.io.Serializable {

	// Fields

	/**
	 * com.xteam.asc4j.module.entities
	 * PurviewFunNode.java   long
	 * Administrator
	 */
	private static final long serialVersionUID = -278100291914748956L;

	private String id;

	private String pfunId;

	private String funcode;

	private String funtype;

	private String name;

	private String classname;

	private String objname;

	private String func;

	private String remark;

	// Constructors

	/** default constructor */
	public PurviewFunNode() {
	}

	/** minimal constructor */
	public PurviewFunNode(String id) {
		this.id = id;
	}

	/** full constructor */
	public PurviewFunNode(String id, String pfunId, String funcode,
			String funtype, String name, String classname, String objname,
			String func, String remark) {
		this.id = id;
		this.pfunId = pfunId;
		this.funcode = funcode;
		this.funtype = funtype;
		this.name = name;
		this.classname = classname;
		this.objname = objname;
		this.func = func;
		this.remark = remark;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getPfunId() {
		return this.pfunId;
	}

	public void setPfunId(String pfunId) {
		this.pfunId = pfunId;
	}

	public String getFuncode() {
		return this.funcode;
	}

	public void setFuncode(String funcode) {
		this.funcode = funcode;
	}

	public String getFuntype() {
		return this.funtype;
	}

	public void setFuntype(String funtype) {
		this.funtype = funtype;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getClassname() {
		return this.classname;
	}

	public void setClassname(String classname) {
		this.classname = classname;
	}

	public String getObjname() {
		return this.objname;
	}

	public void setObjname(String objname) {
		this.objname = objname;
	}

	public String getFunc() {
		return this.func;
	}

	public void setFunc(String func) {
		this.func = func;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}