package com.xteam.asc4j.module.entities;

/**
 * PurviewUserRole generated by MyEclipse Persistence Tools
 */

public class PurviewUserRole implements java.io.Serializable {

	// Fields

	private String id;

	private String userId;

	private String userName;

	private String roleId;

	private String roleName;

	// Constructors

	/** default constructor */
	public PurviewUserRole() {
	}

	/** minimal constructor */
	public PurviewUserRole(String id) {
		this.id = id;
	}

	/** full constructor */
	public PurviewUserRole(String id, String userId, String userName,
			String roleId, String roleName) {
		this.id = id;
		this.userId = userId;
		this.userName = userName;
		this.roleId = roleId;
		this.roleName = roleName;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

}