package com.xteam.asc4j.module.entities;

/**
 * PurviewRole generated by MyEclipse Persistence Tools
 */

public class PurviewRole implements java.io.Serializable {

	// Fields

	private String id;

	private String proleId;

	private String code;

	private String name;

	private String type;

	private String remark;

	// Constructors

	/** default constructor */
	public PurviewRole() {
	}

	/** minimal constructor */
	public PurviewRole(String id) {
		this.id = id;
	}

	/** full constructor */
	public PurviewRole(String id, String proleId, String code, String name,
			String type, String remark) {
		this.id = id;
		this.proleId = proleId;
		this.code = code;
		this.name = name;
		this.type = type;
		this.remark = remark;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getProleId() {
		return this.proleId;
	}

	public void setProleId(String proleId) {
		this.proleId = proleId;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}