package com.xteam.asc4j.module.entities;

/**
 * PurviewDataRule generated by MyEclipse Persistence Tools
 */

public class PurviewDataRule implements java.io.Serializable {

	// Fields

	/**
	 * com.xteam.asc4j.module.entities
	 * PurviewDataRule.java   long
	 * Administrator
	 */
	private static final long serialVersionUID = -689523844260217009L;

	private String druleId;

	private String pdruleId;

	private String drtypeId;

	private String drtypeName;

	private String code;

	private String name;

	private String rule;

	private String remark;

	// Constructors

	/** default constructor */
	public PurviewDataRule() {
	}

	/** minimal constructor */
	public PurviewDataRule(String druleId) {
		this.druleId = druleId;
	}

	/** full constructor */
	public PurviewDataRule(String druleId, String pdruleId, String drtypeId,
			String drtypeName, String code, String name, String rule,
			String remark) {
		this.druleId = druleId;
		this.pdruleId = pdruleId;
		this.drtypeId = drtypeId;
		this.drtypeName = drtypeName;
		this.code = code;
		this.name = name;
		this.rule = rule;
		this.remark = remark;
	}

	// Property accessors

	public String getDruleId() {
		return this.druleId;
	}

	public void setDruleId(String druleId) {
		this.druleId = druleId;
	}

	public String getPdruleId() {
		return this.pdruleId;
	}

	public void setPdruleId(String pdruleId) {
		this.pdruleId = pdruleId;
	}

	public String getDrtypeId() {
		return this.drtypeId;
	}

	public void setDrtypeId(String drtypeId) {
		this.drtypeId = drtypeId;
	}

	public String getDrtypeName() {
		return this.drtypeName;
	}

	public void setDrtypeName(String drtypeName) {
		this.drtypeName = drtypeName;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRule() {
		return this.rule;
	}

	public void setRule(String rule) {
		this.rule = rule;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}