package com.xteam.asc4j.module.entities;

/**
 * PurviewUser generated by MyEclipse Persistence Tools
 */

public class PurviewUser implements java.io.Serializable {

	// Fields

	private String id;

	private String ucode;

	private String uname;

	private String password;

	private String nickName;

	private String tel;

	private String phone;

	private String address;

	private String pstcode;

	private String remark;

	private String isenable;

	private String issys;

	// Constructors

	/** default constructor */
	public PurviewUser() {
	}

	/** minimal constructor */
	public PurviewUser(String id) {
		this.id = id;
	}

	/** full constructor */
	public PurviewUser(String id, String ucode, String uname, String password,
			String nickName, String tel, String phone, String address,
			String pstcode, String remark, String isenable, String issys) {
		this.id = id;
		this.ucode = ucode;
		this.uname = uname;
		this.password = password;
		this.nickName = nickName;
		this.tel = tel;
		this.phone = phone;
		this.address = address;
		this.pstcode = pstcode;
		this.remark = remark;
		this.isenable = isenable;
		this.issys = issys;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUcode() {
		return this.ucode;
	}

	public void setUcode(String ucode) {
		this.ucode = ucode;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPstcode() {
		return this.pstcode;
	}

	public void setPstcode(String pstcode) {
		this.pstcode = pstcode;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getIsenable() {
		return this.isenable;
	}

	public void setIsenable(String isenable) {
		this.isenable = isenable;
	}

	public String getIssys() {
		return this.issys;
	}

	public void setIssys(String issys) {
		this.issys = issys;
	}

}