package com.xteam.asc4j.module.entities;

/**
 * PurviewRoleFunDatarule generated by MyEclipse Persistence Tools
 */

public class PurviewRoleFunDatarule implements java.io.Serializable {

	// Fields

	private String id;

	private String roleId;

	private String roleName;

	private String funId;

	private String funName;

	private Integer funPlist;

	private String druleId;

	private String dataName;

	private Integer dataPlist;

	// Constructors

	/** default constructor */
	public PurviewRoleFunDatarule() {
	}

	/** minimal constructor */
	public PurviewRoleFunDatarule(String id) {
		this.id = id;
	}

	/** full constructor */
	public PurviewRoleFunDatarule(String id, String roleId, String roleName,
			String funId, String funName, Integer funPlist, String druleId,
			String dataName, Integer dataPlist) {
		this.id = id;
		this.roleId = roleId;
		this.roleName = roleName;
		this.funId = funId;
		this.funName = funName;
		this.funPlist = funPlist;
		this.druleId = druleId;
		this.dataName = dataName;
		this.dataPlist = dataPlist;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getFunId() {
		return this.funId;
	}

	public void setFunId(String funId) {
		this.funId = funId;
	}

	public String getFunName() {
		return this.funName;
	}

	public void setFunName(String funName) {
		this.funName = funName;
	}

	public Integer getFunPlist() {
		return this.funPlist;
	}

	public void setFunPlist(Integer funPlist) {
		this.funPlist = funPlist;
	}

	public String getDruleId() {
		return this.druleId;
	}

	public void setDruleId(String druleId) {
		this.druleId = druleId;
	}

	public String getDataName() {
		return this.dataName;
	}

	public void setDataName(String dataName) {
		this.dataName = dataName;
	}

	public Integer getDataPlist() {
		return this.dataPlist;
	}

	public void setDataPlist(Integer dataPlist) {
		this.dataPlist = dataPlist;
	}

}