package com.xteam.asc4j.module.entities;

/**
 * PurviewFunDtype generated by MyEclipse Persistence Tools
 */

public class PurviewFunDtype implements java.io.Serializable {

	// Fields

	private String id;

	private String funId;

	private String funName;

	private String drtypeId;

	private String drtypeName;

	// Constructors

	/** default constructor */
	public PurviewFunDtype() {
	}

	/** minimal constructor */
	public PurviewFunDtype(String id) {
		this.id = id;
	}

	/** full constructor */
	public PurviewFunDtype(String id, String funId, String funName,
			String drtypeId, String drtypeName) {
		this.id = id;
		this.funId = funId;
		this.funName = funName;
		this.drtypeId = drtypeId;
		this.drtypeName = drtypeName;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getFunId() {
		return this.funId;
	}

	public void setFunId(String funId) {
		this.funId = funId;
	}

	public String getFunName() {
		return this.funName;
	}

	public void setFunName(String funName) {
		this.funName = funName;
	}

	public String getDrtypeId() {
		return this.drtypeId;
	}

	public void setDrtypeId(String drtypeId) {
		this.drtypeId = drtypeId;
	}

	public String getDrtypeName() {
		return this.drtypeName;
	}

	public void setDrtypeName(String drtypeName) {
		this.drtypeName = drtypeName;
	}

}