package com.xteam.asc4j.module.entities;

/**
 * PurviewDataType generated by MyEclipse Persistence Tools
 */

public class PurviewDataType implements java.io.Serializable {

	// Fields

	/**
	 * com.xteam.asc4j.module.entities
	 * PurviewDataType.java   long
	 * Administrator
	 */
	private static final long serialVersionUID = 3604589095931830294L;

	private String id;

	private String code;

	private String typeName;

	private String remark;

	// Constructors

	/** default constructor */
	public PurviewDataType() {
	}

	/** minimal constructor */
	public PurviewDataType(String id) {
		this.id = id;
	}

	/** full constructor */
	public PurviewDataType(String id, String code, String typeName,
			String remark) {
		this.id = id;
		this.code = code;
		this.typeName = typeName;
		this.remark = remark;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}